# Generated by Django 4.2.4 on 2023-11-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mc_Donalds', '0002_alter_productorder_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
